import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import ContentWrapper from "@/Components/ContentWrapper";
import Footer from "@/Components/Footer";

const font = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        <ContentWrapper>
          <Header />
          {children}
        </ContentWrapper>
        <Footer />
      </body>
    </html>
  );
}
